/**
 * The generated-by header — decoration on the surface, safety interlock underneath.
 *
 * RAIL 1 depends on it: a target file that does NOT carry the marker was written by a
 * human, and we refuse to overwrite it. Clobbering hand-written code is unrecoverable,
 * so an accidental filename collision has to be loud rather than destructive.
 */

/**
 * The literal that identifies our output. Deliberately SEPARATE from the header
 * template: the rendered header carries a timestamp and a note path, so it can never be
 * compared byte-for-byte against an existing file. The marker is the stable part, and
 * changing it strands every previously-tangled artifact behind rail 1 — which is the
 * safe direction (refuse), but it means the setting is not one to edit casually.
 */
export const DEFAULT_MARKER = "GENERATED by obsidian-execute-code";

export const DEFAULT_HEADER_TEMPLATE = [
	"{{comment}} " + DEFAULT_MARKER + " (tangle) from `{{note}}` — do not edit.",
	"{{comment}} Edit the note and re-tangle; this file is overwritten. [{{date}}]",
].join("\n");

export interface HeaderVars {
	/** Vault-relative path of the source note. */
	note: string;
	/** The note's `uid` frontmatter, when it has one. */
	uid?: string;
	/** ISO timestamp of this tangle. */
	date: string;
	/** The line-comment token for the artifact's language. */
	comment: string;
}

export function renderHeader(template: string, vars: HeaderVars): string {
	const body = template.replace(/\{\{\s*(note|uid|date|comment)\s*\}\}/g, (_m, key: string) => {
		const v = (vars as unknown as Record<string, string | undefined>)[key];
		return v === undefined ? "" : String(v);
	});
	return body.endsWith("\n") ? body : body + "\n";
}

/**
 * Rail 1's test. Looks only at the head of the file: a marker buried a thousand lines
 * down is not a claim of authorship, and reading the whole of a large artifact to
 * decide whether we may write it is wasted work.
 */
export function looksGenerated(existingContent: string, marker: string): boolean {
	if (!marker || !marker.trim()) return false; // an empty marker must not make every file overwritable
	return existingContent.slice(0, 4096).includes(marker);
}

/**
 * Split our own header off an artifact and return just the generated body.
 *
 * Needed because the default header carries a TIMESTAMP. Comparing whole files to
 * decide "has anything changed?" would therefore always say yes, and every sweep would
 * rewrite every artifact — churning mtimes, waking file watchers, and (the reason this
 * was worth fixing rather than living with) invalidating any freshness check that
 * compares a generated file's mtime against its source.
 *
 * Returns null when the header cannot be located, which callers treat as "assume
 * changed" — the safe direction, since a spurious rewrite costs an mtime and a missed
 * one would leave a stale artifact.
 */
export function stripGeneratedHeader(content: string, marker: string): string | null {
	if (!looksGenerated(content, marker)) return null;
	// We always emit `header + "\n" + body`, and the header itself ends in a newline, so
	// the blank line between them is the boundary.
	const i = content.indexOf("\n\n");
	return i === -1 ? null : content.slice(i + 2);
}
